denoising_net: resnet
hidden_dim: 64
dropout_prob: 0 
n_blocks: 3
model_type: conditional_latent # conditional_latent, factorized_latent, learnt_size_factor
embed_time: True
embed_size_factor: True
embedding_dim: 32
conditional: True
embed_condition: True
normalization: none
multimodal: False
is_binarized: False