cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: scgm
project_slug_no_hyphen: scgm
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: richtertill
creator_github_username: richtertill
is_github_repo: false
is_repo_private: false
is_github_orga: false
full_name: Till Richter
email: till-richter@gmx.de
project_name: scgm
project_short_description: scgm. A cookietemple based .
version: 0.1.0
license: MIT
