dataset_path: ../project_folder/datasets/processed/dentategyrus.h5ad
layer_key: X_counts
covariate_keys: [clusters, Age]
subsample_frac: 1
encoder_type: "learnt_autoencoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.90, 0.05, 0.05]
cov_embedding_dimensions: 100
multimodal: False
is_binarized: False 
theta_covariate: None
size_factor_covariate: clusters