dataset_path: ../project_folder/datasets/processed_full_genome/hlca_core/hlca_core_train.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
subsample_frac: 1
encoder_type: "learnt_autoencoder"
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: False
is_binarized: False