dataset_path: ../project_folder/datasets/processed/pbmc68k.h5ad
layer_key: X_counts
covariate_keys: [celltype]
conditioning_covariate: celltype
subsample_frac: 1
encoder_type: "learnt_encoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: False