dataset_path: ../project_folder/datasets/processed_full_genome/tabula_muris/tabula_muris_train.h5ad
layer_key: X_counts
covariate_keys: [tissue]
conditioning_covariate: tissue
subsample_frac: 1
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: False
is_binarized: False