dataset_path: ../project_folder/datasets/processed_full_genome/tabula_muris/tabula_muris_train.h5ad
layer_key: X_counts
covariate_keys: [mouse.id, tissue]
subsample_frac: 1
encoder_type: "learnt_autoencoder"
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: False
is_binarized: False 
# Additions
theta_covariate: None
size_factor_covariate: mouse.id