# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 10
    
    n_trials: 10

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:
      dataset.cov_embedding_dimensions: choice(128, 256)

      denoising_module.embedding_dim: choice(128, 256)
      denoising_module.No: choice(2, 3, 4)

      generative_model.learning_rate: choice(0.0001) 
      generative_model.weight_decay: choice(0.00001, 0.000001) 
      generative_model.antithetic_time_sampling: choice(True, False)
      generative_model.sigma: choice(0, 0.0001, 0.001, 0.01, 0.1)

      training_config.batch_size: choice(128, 256, 512)
