# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 3
    
    n_trials: 3

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:
      dataset.cov_embedding_dimensions: choice(128, 256)

      denoising_module.embedding_dim: choice(128, 256)
      denoising_module.normalization: choice(batch, none)

      generative_model.learning_rate: choice(0.0001, 0.001) 
      generative_model.weight_decay: choice(0.00001, 0.000001) 
      generative_model.antithetic_time_sampling: choice(True, False)
      generative_model.pretraining_encoder_epochs: choice(200)
      generative_model.sigma: choice(0.001, 0.01, 0.1, 0.2)

      training_config.batch_size: choice(128, 256)

      dataset.encoder_type: choice(learnt_encoder)
