# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 25
    
    n_trials: 25

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:
      denoising_module.w: choice(32, 64, 128, 256)
      generative_model.learning_rate: choice(0.0001, 0.001)
      generative_model.noise_schedule: choice(fixed_linear, learned_linear)
      generative_model.gamma_min: range(-5., -1., step=1)
      generative_model.gamma_max: range(1., 5., step=1)
      generative_model.antithetic_time_sampling: choice(True, False)
      generative_model.scaling_method: choice(log_normalization, z_score_normalization, minmax_normalization)
      training_config.batch_size: choice(32, 128, 256, 512)
