# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random 
  - override /hydra/sweeper: optuna 
  
optimized_metric: wasserstein_distance

hydra:

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 40
    
    n_trials: 40

    sampler: 
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:
      denoising_module.hidden_dim: choice(64, 128)
      generative_model.scaling_method: choice(log_normalization, z_score_normalization)
      generative_model.learning_rate: choice(0.0001, 0.005, 0.001) 
      generative_model.weight_decay: choice(0.01, 0.001, 0.0001) 
      generative_model.noise_schedule: choice(learnt_linear)
      generative_model.gamma_min: range(-5., -1., step=1)
      generative_model.gamma_max: range(1., 5., step=1)
      generative_model.antithetic_time_sampling: choice(True, False)
      generative_model.pretraining_encoder_epochs: choice(150)
      training_config.batch_size: choice(64, 128, 256)
      dataset.encoder_type: choice(log_gexp, learnt)
