args:
  # General training config 
  train: True  # Whether to train the model 
  experiment_name: try_experiment_eb 
  task: cell_generation # task (cell_generation or perturbation_modelling)
  dataset_path: ../datasets/scrnaseq_dataset/eb_phate.h5ad
  batch_size: 256  
  cov_embedding_dimensions: Null
  resume: False
  use_pca: False
  n_dimensions: Null
  pretrained_generative: False
  chekpoint_path: Null  
  one_hot_encode_features: True
  layer: X_norm
  
  # CHANGE 
  # Perturbation setting specific
  covariate_keys: [experimental_time]
  split_rates: [0.90, 0.05, 0.05]
  subsample_frac: 1

  # General model 
  generative_model: diffusion  
  denoising_model: mlp

  # Checkpoint kwargs 
  checkpoint_kwargs: 
    filename: epoch_{epoch:01d}
    monitor: valid/loss
    mode: min               
    every_n_epochs: 1
    save_last: True
    auto_insert_metric_name: False

  # Early stopping kwargs 
  early_stopping_kwargs: 
    monitor: train/loss
    patience: 30
    mode: min
    min_delta: 0.
    verbose: False
    strict: True
    check_finite: True
    stopping_threshold: Null
    divergence_threshold: Null
    check_on_train_epoch_end: Null

  # Logger kwargs
  logger_kwargs: 
    offline: True
    id: Null 
    anonymous: Null 
    project: celldreamer
    log_model: False 

  # CHANGE   
  # Denoising model specific 
  denoising_module_kwargs: 
    hidden_dims: [512]
    time_embed_size: 50 
    dropout: False
    dropout_p: 0
    batch_norm: True
    gamma_min: -5.0
    gamma_max: 3.0
    
  # CHANGE      
  # Diffusion model specific
  generative_model_kwargs: 
    learning_rate: 0.001 
    weight_decay: 0.0001 
    noise_schedule: learned_linear
    gamma_min: -5.0
    gamma_max: 3.0
    antithetic_time_sampling: True 
    scaling_method: log_normalization
    z0_from_x_kwargs:
      dims: [512]
      batch_norm:  True
      dropout: False 
      dropout_p: 0.0
      final_activation: Null
                  
  # Autoencoder trainer hparams
  trainer_kwargs:
    max_epochs: 500
    accelerator: gpu 
    devices: 1
    check_val_every_n_epoch: 1
    log_every_n_steps: 1
    detect_anomaly: False
    deterministic: False
                    