dataset_path: ../datasets/processed/lung_atlas.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
subsample_frac: 1
encoder_type: "learnt_autoencoder"
target_max: 1
target_min: -1
one_hot_encode_features: True
split_rates: [0.90, 0.05, 0.05]
cov_embedding_dimensions: Null