dataset_path: ../../project_folder/datasets/processed_full_genome/dentategyrus/dentategyrus_train.h5ad
layer_key: X_counts
covariate_keys: [clusters]
subsample_frac: 1
one_hot_encode_features: False
normalization_type: log_gexp
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
is_binarized: False 
theta_covariate: clusters
size_factor_covariate: clusters
guidance_weights:
  clusters: 1

