dataset_path: ../datasets/processed/dentategyrus.h5ad
layer_key: X_counts
covariate_keys: [clusters]
conditioning_covariate: clusters
subsample_frac: 1
encoder_type: "learnt_encoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.90, 0.05, 0.05]
cov_embedding_dimensions: 100