dataset_path: ../project_folder/datasets/processed/dentategyrus.h5ad
layer_key: X_counts
covariate_keys: [clusters]
subsample_frac: 1
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: False
is_binarized: False 
theta_covariate: clusters
size_factor_covariate: clusters
guidance_weights:
  clusters: 1

