dataset_path: ../project_folder/datasets/processed/atac/neurips_multiome.h5mu
layer_key: X_counts
covariate_keys: [cell_type]
subsample_frac: 1
encoder_type: "learnt_autoencoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.80, 0.10, 0.10]
cov_embedding_dimensions: 100
multimodal: True
is_binarized: False 
theta_covariate: cell_type
size_factor_covariate: cell_type
guidance_weights:
  cell_type: 1