dataset_path: ../datasets/processed/neurips.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
subsample_frac: 0.3
encoder_type: "learnt_encoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.90, 0.05, 0.05]
cov_embedding_dimensions: 100