dataset_path: ../project_folder/datasets/processed_full_genome/pbmc3k.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
subsample_frac: 1
encoder_type: "learnt_encoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.80, 0.10, 0.10]
multimodal: False
is_binarized: False 