dataset_path: ../project_folder/datasets/processed/atac/pbmc10k_rna_multiome_train.h5ad
layer_key: X_counts
covariate_keys: [cell_type]
subsample_frac: 1
encoder_type: "learnt_autoencoder"
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: True
is_binarized: True 
theta_covariate: cell_type
size_factor_covariate: cell_type
guidance_weights:
  cell_type: 1