dataset_path: ../project_folder/datasets/processed_full_genome/tabula_muris/tabula_muris_train.h5ad
layer_key: X_counts
covariate_keys: [tissue]
conditioning_covariate: tissue
subsample_frac: 1
encoder_type: "learnt_encoder"
target_max: 1
target_min: -1
one_hot_encode_features: False
split_rates: [0.90, 0.10]
multimodal: False
is_binarized: False 