denoising_net: resnet
hidden_dim: 512
dropout_prob: 0
n_blocks: 2
model_type: conditional_latent # conditional_latent, factorized_latent, learnt_size_factor
conditional: True
embed_time: True
embed_size_factor: True
embed_condition: True
embedding_dim: 256
normalization: Null
