learning_rate: 0.001 
weight_decay: 0.00001 
noise_schedule: learnt_linear 
gamma_min: -5.0
gamma_max: 3.0
antithetic_time_sampling: True 
scaling_method: log_normalization
x0_from_x_kwargs:
  dims: [256, 256]
  batch_norm:  True
  dropout: False 
  dropout_p: 0.0
pretrain_encoder: False
pretraining_encoder_epochs: 0
use_tanh_encoder: False